### ISSUE TITLE
Cannot Edit Times for  "Time> Begin/End > night mode"

### ISSUE THREAD

**Issue by RKF-FKR** [merlinschumacher/esp8266-clock#6]
Using ESP8266 DMA build

Web Browsers tried: 
MAC Chrome
MAC Safari
MAC Firefox
Win IE 

After changing the preferred times and saving (shows success) I then refresh the page - the original times are still there and no changes are implemented.

I have tried two different ESP8266 and multiple browsers on multiple devices without success.

I tried to edit the line 180 and line 183 on config.cpp and compile with platformIO but the compile failed (actually on all env's)

Is there a debug dump I can provide?

**Comment by merlinschumacher** [comment]
I will checkout why this won't work.

**Comment by RKF-FKR** [comment]
Hello Merlin - I think I have solved the above issue - to make the time change effective, you must TAB across each field until you TAB past all of the night mode section completely.  Then it will allow to save.
